import turtle

tortuguita=turtle.Turtle()
tortuguita.pensize(15)
tortuguita.pencolor("Yellow")
tortuguita.shape("square")
tortuguita.forward(100)
tortuguita.right(90)
tortuguita.forward(100)
tortuguita.right(90)
tortuguita.forward(100)
tortuguita.right(90)
tortuguita.forward(190)
tortuguita.right(90)
tortuguita.forward(100)

tortuguita.up()
tortuguita.goto(120, -100)
tortuguita.down()


tortuguita.pensize(15)
tortuguita.pencolor("light pink")
tortuguita.shape("square")
tortuguita.right(270)
tortuguita.forward(190)
tortuguita.right(90)
tortuguita.forward(100)
tortuguita.right(90)
tortuguita.forward(190)
tortuguita.right(180)
tortuguita.forward(100)
tortuguita.right(270)
tortuguita.forward(100)

tortuguita.up()
tortuguita.goto(245, -100)
tortuguita.down()

tortuguita.pensize(15)
tortuguita.pencolor("light blue")
tortuguita.shape("square")
tortuguita.right(90)
tortuguita.forward(190)
tortuguita.right(90)
tortuguita.forward(98)
tortuguita.right(45)
tortuguita.forward(30)
tortuguita.right(45)
tortuguita.forward(50)
tortuguita.right(45)
tortuguita.forward(35)
tortuguita.right(45)
tortuguita.forward(95)
tortuguita.right(180)
tortuguita.forward(95)
tortuguita.right(45)
tortuguita.forward(30)
tortuguita.right(45)
tortuguita.forward(52)
tortuguita.right(45)
tortuguita.forward(30)
tortuguita.right(45)
tortuguita.forward(95)

tortuguita.up()
tortuguita.goto(385, -100)
tortuguita.down()


tortuguita.pensize(15)
tortuguita.pencolor("light green")
tortuguita.shape("square")
tortuguita.right(90)
tortuguita.forward(190)
tortuguita.right(90)
tortuguita.forward(100)
tortuguita.right(45)
tortuguita.forward(30)
tortuguita.right(45)
tortuguita.forward(50)
tortuguita.right(45)
tortuguita.forward(30)
tortuguita.right(45)
tortuguita.forward(97)
tortuguita.right(180)
tortuguita.forward(97)
tortuguita.right(50)
tortuguita.forward(25)
tortuguita.right(40)
tortuguita.forward(80)

tortuguita.up()
tortuguita.goto(530, -100)
tortuguita.down()

tortuguita.shape("square")
tortuguita.pensize(15)
tortuguita.pencolor("Cyan")
tortuguita.right(270)
tortuguita.forward(130)
tortuguita.right(180)
tortuguita.forward(65)
tortuguita.right(90)
tortuguita.forward(190)
tortuguita.right(90)
tortuguita.forward(65)
tortuguita.right(180)
tortuguita.forward(130)

tortuguita.up()
tortuguita.goto(805, -100)
tortuguita.down()

tortuguita.shape("square")
tortuguita.pensize(15)
tortuguita.pencolor("purple")
tortuguita.right(0)
tortuguita.forward(120)
tortuguita.right(90)
tortuguita.forward(95)
tortuguita.right(90)
tortuguita.forward(120)
tortuguita.right(180)
tortuguita.forward(120)
tortuguita.right(90)
tortuguita.forward(95)
tortuguita.right(90)
tortuguita.forward(120)

tortuguita.up()
tortuguita.goto(850, -100)
tortuguita.down()


tortuguita.shape("square")
tortuguita.pensize(15)
tortuguita.pencolor("grey")
tortuguita.right(0)
tortuguita.forward(130)
tortuguita.right(180)
tortuguita.forward(130)
tortuguita.right(90)
tortuguita.forward(190)

tortuguita.up()
tortuguita.goto(995, -100)
tortuguita.down()

tortuguita.pensize(15)
tortuguita.pencolor("light pink")
tortuguita.shape("square")
tortuguita.forward(190)
tortuguita.right(90)
tortuguita.forward(100)
tortuguita.right(90)
tortuguita.forward(190)
tortuguita.right(180)
tortuguita.forward(100)
tortuguita.right(270)
tortuguita.forward(100)


 
